# Generated by Django 3.1.4 on 2020-12-02 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(help_text='Database ID', primary_key=True, serialize=False)),
                ('tid', models.IntegerField(help_text='Telegram API ID', unique=True)),
                ('token', models.CharField(help_text='Telegram API Token', max_length=46, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Running'), (0, 'Stopped')], default=0)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bots',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trigger', models.CharField(help_text='Text which will trigger command', max_length=128)),
                ('reply_text', models.TextField(help_text='Text to be sent when command is triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bots.bot')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commands',
            },
        ),
    ]
