# Generated by Django 3.1.4 on 2020-12-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='username',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='tid',
            field=models.IntegerField(editable=False, help_text='Telegram API ID', unique=True),
        ),
    ]
