# Generated by Django 3.1.4 on 2020-12-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20201202_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='bot_id',
            new_name='bot',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
