# Generated by Django 3.1.4 on 2021-03-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20201205_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_tid', models.IntegerField(editable=False, help_text='Message sender tid', unique=True)),
                ('text', models.TextField(max_length=2048)),
                ('date', models.DateTimeField(verbose_name='Date and time message was sent')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
