# Generated by Django 3.1.4 on 2021-03-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_auto_20210316_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.commandtype'),
            preserve_default=False,
        ),
    ]
