# Generated by Django 3.1.4 on 2021-03-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_auto_20210316_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineKeyboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inline_keyboards',
            },
        ),
        migrations.CreateModel(
            name='InlinKeyboardButton',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('url', models.URLField(blank=True, default='')),
                ('callback_data', models.CharField(blank=True, default='', max_length=64)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bots.inlinekeyboard')),
            ],
            options={
                'db_table': 'inline_keyboard_buttons',
            },
        ),
    ]
