# Generated by Django 3.1.4 on 2021-03-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_auto_20210316_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InlinKeyboardButton',
            new_name='InlineKeyboardButton',
        ),
    ]
