# Generated by Django 3.1.4 on 2021-03-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_auto_20210317_0844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandType',
            new_name='ResponseType',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='type',
            new_name='response_type',
        ),
        migrations.AlterModelTable(
            name='responsetype',
            table='response_types',
        ),
    ]
