# Generated by Django 3.1.4 on 2021-03-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_auto_20210317_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackHandler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trigger', models.CharField(max_length=64)),
                ('reply_text', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bots.bot')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bots.datasource')),
                ('response_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bots.responsetype')),
            ],
            options={
                'db_table': 'callback_handlers',
            },
        ),
    ]
