# Generated by Django 3.1.4 on 2021-03-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0018_auto_20210317_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.bot'),
            preserve_default=False,
        ),
    ]
