# Generated by Django 3.1.7 on 2021-03-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0019_message_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackhandler',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='callbackhandler',
            name='response_type',
        ),
        migrations.RemoveField(
            model_name='command',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='command',
            name='response_type',
        ),
        migrations.AddField(
            model_name='command',
            name='reply_json_url',
            field=models.URLField(blank=True, default='', help_text='Url to json data'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(editable=False, help_text='Telegram API Token', max_length=46, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='bot',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.bot'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(editable=False, verbose_name='Date and time message was sent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(editable=False),
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='DataSourceType',
        ),
        migrations.DeleteModel(
            name='ResponseType',
        ),
    ]
