# Generated by Django 3.1.7 on 2021-03-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0020_auto_20210327_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinekeyboard',
            name='bot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.bot'),
        ),
    ]
