# Generated by Django 3.1.7 on 2021-03-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0021_inlinekeyboard_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlinekeyboard',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inlinekeyboardbutton',
            name='keyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buttons', to='bots.inlinekeyboard'),
        ),
    ]
