# Generated by Django 3.1.7 on 2021-03-31 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0022_auto_20210329_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='inline_keyboard',
        ),
        migrations.RemoveField(
            model_name='inlinekeyboardbutton',
            name='keyboard',
        ),
        migrations.AddField(
            model_name='inlinekeyboardbutton',
            name='command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buttons', to='bots.command'),
            preserve_default=False,
        ),
    ]
