# Generated by Django 3.1.7 on 2021-04-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0023_auto_20210331_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlinekeyboardbutton',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='bots.command'),
        ),
    ]
