# Generated by Django 3.1.7 on 2021-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0024_auto_20210401_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackhandler',
            name='reply_img_url',
            field=models.TextField(blank=True, default='', help_text='Url to image'),
        ),
    ]
