# Generated by Django 3.1.7 on 2021-06-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0025_callbackhandler_reply_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(help_text='Telegram API Token', max_length=46, unique=True),
        ),
    ]
